name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: eu-west-2

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Zip Lambda function
        run: zip lambda.zip lambda.py
      
      - name: Calculate SHA256 hash of lambda.zip
        run: |
         HASH=$(sha256sum lambda.zip | awk '{ print $1 }')
         echo "SHA256 hash (base64):"
         echo "$HASH" | xxd -r -p | base64


      - name: Upload Lambda zip to S3
        run: aws s3 cp lambda.zip s3://mt-s3-lon/mt-lambda/lambda.zip
